function y = doFilter20(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 13-Sep-2018 17:16:22

persistent Hd;

if isempty(Hd)
    
    Fpass = 20;  % Passband Frequency
    Fstop = 25;  % Stopband Frequency
    Apass = 1;   % Passband Ripple (dB)
    Astop = 60;  % Stopband Attenuation (dB)
    Fs    = 52;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'kaiserwin');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

