function y = doFilterBody(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 13-Sep-2018 17:33:34

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.3;  % Stopband Frequency
    Fpass = 0.5;  % Passband Frequency
    Astop = 60;   % Stopband Attenuation (dB)
    Apass = 1;    % Passband Ripple (dB)
    Fs    = 52;   % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

